name: CFN-NAG Security Scan

on: [push]

jobs:
  ## cfn-nag security scan
  security-scan-nag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: grolston/cfn-security@master
      with:
        cloudformation_directory: './cloudformation/' ## change to your template directory
        scanner: "cfn-nag"
